const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rules=[],scanner={},signals=[],chartData=null,chart=null,candles=null,volumeSeries=null,maSeries={},macdChart=null,macdSeries={},selected=null,replayTimer=null,ws=null;
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:d}):'—';
const pct=n=>Number.isFinite(n)?`${n>0?'+':''}${n.toFixed(2)}%`:'—';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',5500)}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d}
function action(id,fn){$(id).onclick=async()=>{const b=$(id);b.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{b.disabled=false}}}
function page(id){document.querySelectorAll('.page').forEach(e=>e.classList.toggle('active',e.id===id));document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.page===id));$('pageTitle').textContent={desk:'市场与信号',analysis:'K线分析',patterns:'监控模式',review:'交易复盘',push:'提醒与设置'}[id];if(id==='review')loadReview().catch(e=>toast(e.message));if(id==='push')loadMobile().catch(e=>toast(e.message));if(id==='analysis'&&chart)chart.resize($('chart').clientWidth,400)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));
function renderStatus(s){$('monitorStatus').textContent=({running:'监控中',sleeping:'休市等待',disconnected:'连接中断',connecting:'连接中',initializing:'初始化'})[s.status]||s.status;$('statusMessage').textContent=s.status_message;$('coverage').textContent=fmt(s.coverage||0,0);$('universe').textContent=`共 ${s.total_stocks} 只主板证券`;$('signalCount').textContent=fmt(s.alert_count,0);$('lastScan').textContent=s.last_scan_time?.slice(11)||'—';$('scanDuration').textContent=`本轮 ${s.scan_seconds||0} 秒 · ${s.scan_count} 轮`;$('desktopEnabled').checked=s.system_notifications?.enabled??false}
async function loadSignals(){signals=(await api('/api/alerts?limit=150')).alerts;renderSignals()}
function renderSignals(){$('signalList').innerHTML=signals.length?signals.map((a,i)=>`<div class="signal" data-index="${i}"><div class="top"><b>${esc(a.code)}　${esc(a.name)}</b><span class="badge">${esc(a.type)}</span></div><p>${esc(a.detail)}</p><small>${esc(a.timestamp)} · HK$ ${fmt(a.price,3)}</small></div>`).join(''):'<div class="empty">暂无持久化信号<br>开盘后完成预热，满足规则的异动会显示在这里。</div>';$('signalList').querySelectorAll('[data-index]').forEach(el=>el.onclick=()=>selectSignal(signals[+el.dataset.index]))}
async function loadMarket(){const d=await api('/api/market');$('marketAsOf').textContent=d.asof?.slice(11)||'等待首轮行情';for(const [id,rows] of [['marketList',d.rows.slice(0,12)],['watchList',d.watchlist]]){$(id).innerHTML=rows.length?rows.map(r=>`<div class="market-row" data-code="${esc(r.code)}"><div>${esc(r.name)}<small>${esc(r.code)}</small></div><span>${fmt(r.price,3)}</span><span class="${r.change_pct>=0?'up':'down'}">${pct(r.change_pct)}</span></div>`).join(''):'<div class="empty">暂无扫描数据</div>';$(id).querySelectorAll('[data-code]').forEach(el=>el.onclick=()=>{selected=null;$('stockCode').value=el.dataset.code;page('analysis');loadChart().catch(e=>toast(e.message))})}}
function selectSignal(a){selected=a;$('stockCode').value=a.code;$('chartEnd').value=a.timestamp.slice(0,10);$('period').value='K_5M';$('selectedSignal').innerHTML=`<b>${esc(a.title)}</b><pre>${esc(a.detail)}</pre><small>${esc(a.timestamp)} · 触发参数已随信号留档</small><pre>${esc(JSON.stringify(a.pattern||{},null,2))}</pre>`;page('analysis');loadChart().catch(e=>toast(e.message))}
const chartOptions={layout:{background:{color:'#121a23'},textColor:'#8b9bab'},grid:{vertLines:{color:'#1d2834'},horzLines:{color:'#1d2834'}},rightPriceScale:{borderColor:'#344050'},timeScale:{borderColor:'#344050',timeVisible:true},crosshair:{mode:0}};
function initCharts(){if(chart)return;chart=LightweightCharts.createChart($('chart'),{...chartOptions,width:$('chart').clientWidth,height:400});candles=chart.addCandlestickSeries({upColor:'#5ae0bf',downColor:'#ff7886',borderVisible:false,wickUpColor:'#5ae0bf',wickDownColor:'#ff7886'});volumeSeries=chart.addHistogramSeries({priceFormat:{type:'volume'},priceScaleId:'volume'});chart.priceScale('volume').applyOptions({scaleMargins:{top:.8,bottom:0}});chart.priceScale('right').applyOptions({scaleMargins:{top:.1,bottom:.25}});for(const [k,c] of Object.entries({ma5:'#f3c66f',ma20:'#70baff',ma60:'#b598ed'}))maSeries[k]=chart.addLineSeries({color:c,lineWidth:1,priceLineVisible:false,lastValueVisible:false});macdChart=LightweightCharts.createChart($('macdChart'),{...chartOptions,width:$('macdChart').clientWidth,height:150});macdSeries.macd=macdChart.addLineSeries({color:'#70baff',lineWidth:1});macdSeries.signal=macdChart.addLineSeries({color:'#f3c66f',lineWidth:1});macdSeries.histogram=macdChart.addHistogramSeries();let syncing=false;for(const [a,b] of [[chart,macdChart],[macdChart,chart]])a.timeScale().subscribeVisibleLogicalRangeChange(range=>{if(!syncing&&range){syncing=true;b.timeScale().setVisibleLogicalRange(range);syncing=false}});new ResizeObserver(()=>{if($('chart').clientWidth){chart.resize($('chart').clientWidth,400);macdChart.resize($('macdChart').clientWidth,150)}}).observe($('chart'))}
async function loadChart(){clearInterval(replayTimer);$('replayPlay').textContent='播放';$('chartError').textContent='正在请求富途历史K线…';chartData=null;if(chart){candles.setData([]);volumeSeries.setData([]);Object.values(maSeries).forEach(s=>s.setData([]));Object.values(macdSeries).forEach(s=>s.setData([]));candles.setMarkers([])}$('analysisCards').innerHTML='';try{const d=await api(`/api/chart?code=${encodeURIComponent($('stockCode').value.trim().toUpperCase())}&period=${$('period').value}&end=${$('chartEnd').value||today()}`);chartData=d;initCharts();$('replaySlider').max=d.bars.length||1;$('replaySlider').value=d.bars.length||1;renderChart(d.bars.length);chart.timeScale().fitContent();$('chartError').textContent=d.bars.length?'':'该日期范围内没有可用K线';$('chartMeta').textContent=`${d.code} · ${d.source} · ${d.adjustment} · ${d.timezone} · ${d.bars.length}根`}catch(e){$('chartError').textContent=e.message;$('chartMeta').textContent='行情不可用';throw e}}
function renderChart(count){if(!chartData||!chart)return;const bars=chartData.bars.slice(0,count),last=bars.at(-1);if(!last)return;candles.setData(bars);volumeSeries.setData(bars.map(b=>({time:b.time,value:b.volume,color:b.close>=b.open?'#285f53':'#633e49'})));for(const k in maSeries)maSeries[k].setData((chartData.series[k]||[]).filter(v=>v.time<=last.time));for(const k in macdSeries)macdSeries[k].setData((chartData.series[k]||[]).filter(v=>v.time<=last.time).map(v=>k==='histogram'?{...v,color:v.value>=0?'#5ae0bf':'#ff7886'}:v));const markers=[];for(const a of chartData.alerts){const stamp=Date.parse(a.timestamp.replace(' ','T')+'Z')/1000;const match=[...bars].reverse().find(b=>b.time<=stamp);if(match&&stamp<=last.time&&stamp>=bars[0].time)markers.push({time:match.time,position:'aboveBar',color:'#f3c66f',shape:'arrowDown',text:a.type})}candles.setMarkers(markers.sort((a,b)=>a.time-b.time));$('replayDate').textContent=last.date;const val=k=>(chartData.series[k]||[]).filter(v=>v.time<=last.time).at(-1)?.value;const ma20=val('ma20'),ma60=val('ma60');const trend=ma20==null||ma60==null?'样本不足':last.close>ma20&&ma20>ma60?'均线上方':last.close<ma20&&ma20<ma60?'均线下方':'均线交错';$('analysisCards').innerHTML=[['价格位置',trend,'当前价 / MA20 / MA60'],['RSI · 14',fmt(val('rsi')),'指数平滑；短样本不显示'],['ATR · 14',fmt(val('atr'),3),'绝对价格波动幅度'],['相对成交量',fmt(val('relative_volume'))+' 倍','本根量 / 此前20根均量']].map(a=>`<div><small>${a[0]}</small><strong>${a[1]}</strong><small>${a[2]}</small></div>`).join('')}
$('replaySlider').oninput=()=>renderChart(+$('replaySlider').value);$('replayPlay').onclick=()=>{if(replayTimer){clearInterval(replayTimer);replayTimer=null;$('replayPlay').textContent='播放';return}if(!chartData)return;if(+$('replaySlider').value>=chartData.bars.length)$('replaySlider').value=1;$('replayPlay').textContent='暂停';replayTimer=setInterval(()=>{let n=+$('replaySlider').value+1;if(n>chartData.bars.length){clearInterval(replayTimer);replayTimer=null;$('replayPlay').textContent='播放';return}$('replaySlider').value=n;renderChart(n)},450)};$('replayReset').onclick=()=>{clearInterval(replayTimer);replayTimer=null;$('replayPlay').textContent='播放';if(chartData){$('replaySlider').value=chartData.bars.length;renderChart(chartData.bars.length)}};
async function loadPatterns(){const d=await api('/api/patterns');rules=d.patterns;scanner=d.scanner;renderPatterns();$('scanInterval').value=scanner.scan_interval;$('watchCodes').value=scanner.watchlist.join(', ');$('reviewPattern').innerHTML='<option value="">全部模式</option>'+rules.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}
function field(p,k,label,type='number'){return `<label>${label}<input data-key="${k}" type="${type}" value="${esc(p[k])}" step="any"></label>`}
function renderPatterns(){$('patternList').innerHTML=rules.map((p,i)=>`<div class="pattern-card" data-index="${i}"><div class="pattern-head"><input type="checkbox" data-key="enabled" ${p.enabled?'checked':''}><input data-key="name" type="text" value="${esc(p.name)}"><button data-remove="${i}">删除</button></div><div class="pattern-fields"><label>模式类型<select data-key="kind">${[['drop','区间急跌（%）'],['volume','区间放量（股）'],['breakout','向上突破（%）']].map(([v,t])=>`<option value="${v}" ${p.kind===v?'selected':''}>${t}</option>`).join('')}</select></label>${field(p,'threshold','触发阈值')}${field(p,'window_sec','窗口（秒）')}${field(p,'warmup_sec','预热（秒）')}${field(p,'cooldown_sec','冷却（秒）')}${field(p,'min_price','最低股价 HK$')}${field(p,'min_turnover','当日最低成交额 HK$')}${field(p,'min_samples','最少采样数')}${field(p,'recovery_ratio','重新武装比例（0~1）')}<label>监控范围<select data-key="scope"><option value="all" ${p.scope==='all'?'selected':''}>全市场</option><option value="watchlist" ${p.scope==='watchlist'?'selected':''}>仅自选</option></select></label><label><input type="checkbox" data-key="mobile" ${p.mobile?'checked':''}> 允许手机提醒</label></div></div>`).join('');$('patternList').querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{const p=rules[+el.closest('[data-index]').dataset.index];p[el.dataset.key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value});$('patternList').querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{rules.splice(+el.dataset.remove,1);renderPatterns()})}
action('addPattern',()=>{rules.push({id:'custom-'+Date.now(),name:'自定义模式',kind:'breakout',enabled:false,threshold:1,window_sec:600,min_price:0,min_turnover:0,cooldown_sec:600,min_samples:3,warmup_sec:30,recovery_ratio:.7,scope:'watchlist',mobile:true});renderPatterns()});action('savePatterns',async()=>{toast((await api('/api/patterns',{patterns:rules})).message);await loadPatterns()});action('saveScanner',async()=>{scanner=await api('/api/scanner',{scan_interval:Number($('scanInterval').value),watchlist:$('watchCodes').value.split(/[,，\s]+/).filter(Boolean).map(x=>x.toUpperCase())});toast('扫描设置已保存')});action('addWatch',async()=>{const code=$('stockCode').value.trim().toUpperCase();scanner=await api('/api/scanner',{...scanner,watchlist:[...new Set([...scanner.watchlist,code])]});$('watchCodes').value=scanner.watchlist.join(', ');toast('已加入自选')});
async function loadReview(){const q=`date=${$('reviewDate').value}&pattern=${encodeURIComponent($('reviewPattern').value)}`;const d=await api('/api/review?'+q);$('reviewMethod').textContent=d.method;$('reviewGroups').innerHTML=d.groups.map(g=>`<div><small>${esc(g.name)} · ${g.signals}条 / 已复盘${g.reviewed}条</small><strong>${pct(g.mean_15m)}</strong><small>15分钟平均原始变化 · ${g.samples}个有效样本<br>上涨占比 ${fmt(g.positive_rate)}%（非胜率）</small></div>`).join('');$('reviewRows').innerHTML=d.alerts.length?d.alerts.map((a,i)=>`<tr><td>${esc(a.timestamp)}<br><b>${esc(a.code)} ${esc(a.name)}</b></td><td>${esc(a.type)}</td><td>${fmt(a.price,3)}</td>${[300,900,1800].map(h=>`<td>${pct(a.outcomes[h]?.return_pct)}</td>`).join('')}<td><select id="tag${i}">${['待复盘','有效信号','噪声','已跟踪','已忽略'].map(t=>`<option ${a.review.tag===t?'selected':''}>${t}</option>`).join('')}</select><textarea id="note${i}" placeholder="触发背景、计划、执行偏差…">${esc(a.review.note)}</textarea></td><td><button data-note="${i}">保存</button><button data-chart="${i}">K线</button></td></tr>`).join(''):'<tr><td colspan="8"><div class="empty">没有符合筛选条件的信号</div></td></tr>';$('reviewRows').querySelectorAll('[data-note]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.note;try{await api('/api/review/note',{alert_id:d.alerts[i].id,tag:$('tag'+i).value,note:$('note'+i).value});toast('复盘笔记已保存')}catch(e){toast(e.message)}});$('reviewRows').querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>selectSignal(d.alerts[+b.dataset.chart]))}
async function loadMobile(){const d=await api('/api/mobile'),s=d.settings;$('mobileEnabled').checked=s.enabled;$('telegramEnabled').checked=s.telegram_enabled;$('barkEnabled').checked=s.bark_enabled;$('telegramChat').value='';$('telegramChat').placeholder=s.telegram_chat_id_configured?'已保存，留空保留':'接收 Chat ID';$('telegramConfigured').textContent=s.telegram_token_configured?'（已保存）':'';$('barkConfigured').textContent=s.bark_key_configured?'（已保存）':'';$('deliveryList').innerHTML=d.deliveries.length?d.deliveries.map(r=>`<div class="delivery"><span class="${r.success?'up':'down'}">${esc(r.channel)} · ${r.success?'已提交':'失败'}</span><small>　${esc(r.timestamp)}</small><div>${esc(r.detail)}</div></div>`).join(''):'<div class="empty">暂无推送记录。保存配置后可发送测试。</div>'}
action('saveMobile',async()=>{await api('/api/mobile',{enabled:$('mobileEnabled').checked,telegram_enabled:$('telegramEnabled').checked,bark_enabled:$('barkEnabled').checked,telegram_token:$('telegramToken').value.trim(),telegram_chat_id:$('telegramChat').value.trim(),bark_key:$('barkKey').value.trim()});$('telegramToken').value='';$('barkKey').value='';await loadMobile();toast('手机提醒设置已保存')});action('testMobile',async()=>{const d=await api('/api/mobile/test',{});toast(d.results.map(r=>r.channel+'：'+r.detail).join('；'));await loadMobile()});action('testDesktop',async()=>{const r=await api('/api/notifications/test',{});toast(r.success?'测试已提交 Windows':'系统提醒已关闭或尚未就绪')});$('desktopEnabled').onchange=async()=>{try{await api('/api/notifications',{enabled:$('desktopEnabled').checked});toast('系统提醒设置已保存')}catch(e){toast(e.message)}};
action('refreshAlerts',loadSignals);action('loadChart',loadChart);action('loadReview',loadReview);$('exportReview').onclick=()=>window.location='/api/review/export?date='+$('reviewDate').value;$('chartEnd').value=today();$('stockCode').oninput=async()=>{try{const d=await api('/api/stocks?q='+encodeURIComponent($('stockCode').value));$('stockSuggestions').innerHTML=d.stocks.map(r=>`<option value="${esc(r.code)}">${esc(r.name)}</option>`).join('')}catch(e){}};
function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.onopen=()=>{$('connection').className='online';$('connectionText').textContent='实时连接';loadSignals().catch(()=>{})};ws.onclose=()=>{$('connection').className='';$('connectionText').textContent='重连中';setTimeout(connect,3000)};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='status')renderStatus(m.data);if(m.type==='alert'){if(!signals.some(a=>a.id===m.data.id)){signals.unshift(m.data);signals=signals.slice(0,150);renderSignals();toast(m.data.title)}}}}
Promise.all([loadPatterns(),loadSignals(),loadMarket(),api('/api/status').then(renderStatus)]).catch(e=>toast(e.message));connect();setInterval(()=>{if(ws?.readyState===1)ws.send('heartbeat');else api('/api/status').then(renderStatus).catch(()=>{});$('clock').textContent=new Date().toLocaleString('zh-CN',{timeZone:'Asia/Hong_Kong',hour12:false})},5000);setInterval(()=>loadMarket().catch(()=>{}),15000);

$('riskCalculate').onclick=()=>{
    const capital=Number($('riskCapital').value),percent=Number($('riskPercent').value),entry=Number($('riskEntry').value),stopPrice=Number($('riskStop').value),lot=Number($('riskLot').value);
    if (!(capital>0&&percent>0&&percent<=100&&entry>stopPrice&&stopPrice>0&&Number.isInteger(lot)&&lot>0)){toast('请填写有效资金、风险比例和整手股数；做多止损须低于入场价');return}
    const budget=capital*percent/100,shares=Math.floor(Math.min(budget/(entry-stopPrice),capital/entry)/lot)*lot;
    $('riskResult').textContent=`${fmt(shares,0)} 股 / ${fmt(shares/lot,0)} 手 · 名义金额 HK$ ${fmt(shares*entry)} · 价差风险 HK$ ${fmt(shares*(entry-stopPrice))}`;
};
